### ISSUE TITLE
bug: no `useShepherdTour` export from react-shepher

### ISSUE THREAD

**Issue by YashKandalkar** [shepherd-pro/react-shepherd#780]
I saw that there's a hook usage available as shown in the [example](https://react-shepherd.vercel.app/)
But there's no such export from react-shepherd:
<img width="704" alt="image" src="https://github.com/shepherd-pro/react-shepherd/assets/35102959/180c34eb-fdf0-41d0-a9fb-784f712b79d9">

I am on v4.2.0

**Comment by chuckcarpenter** [comment]
Will get a release out this weekend, what a miss on my part. Apologies @YashKandalkar

**Comment by chuckcarpenter** [comment]
Finally got there, need to revamp our release action and packages, but for now https://www.npmjs.com/package/react-shepherd
